/**
 * Tessendorf-style Phillips wave spectrum.
 *
 * Pure math, no Three.js — usable from both the sim layer (CPU buoyancy
 * sampler) and the render layer (GPU IFFT pipeline). Both consumers seed
 * from the same parameters and PRNG so the spectrum is bit-identical
 * across CPU and GPU, which is what keeps buoyancy deterministic when
 * the FFT pipeline lands.
 *
 * The Phillips spectrum (Tessendorf 2001, eq. 23) gives the statistical
 * energy of wind-driven ocean waves at each 2D wavenumber `k`:
 *
 *   P(k) = A · exp(−1/(kL)²) · |k̂·ŵ|² / k⁴
 *
 * where `L = V²/g` is the largest wavelength generated by the wind, `ŵ`
 * is the wind direction, and `A` is an overall amplitude. The squared
 * direction dot-product makes waves running with the wind dominate; the
 * 1/k⁴ tail puts most energy in long wavelengths; the exponential damps
 * waves much longer than `L`.
 *
 * The initial complex amplitudes `h0(k)` are then drawn from
 *
 *   h0(k) = (ξ_r + i·ξ_i) · √(P(k) / 2)
 *
 * with `ξ_r, ξ_i` independent standard-normal samples. This is THE
 * source-of-truth random data for the wave field: every later step (time
 * evolution, IFFT, sampling) is deterministic in `h0`. With a seeded
 * PRNG, the whole simulation is replay-safe.
 */

const TWO_PI = Math.PI * 2

/**
 * mulberry32 — small, fast, well-distributed 32-bit PRNG. Deterministic
 * for a given seed. Used here so both sim and render reach identical
 * `h0(k)` arrays without sharing a global RNG.
 */
export function mulberry32(seed: number): () => number {
  let state = seed >>> 0
  return () => {
    state = (state + 0x6d2b79f5) >>> 0
    let t = state
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/**
 * Box-Muller transform: takes two uniform-(0,1) samples, returns two
 * independent standard-normal samples. The Phillips spectrum needs two
 * normals per wavenumber (real + imaginary parts of h0), so this returns
 * a pair directly.
 *
 * Uses the natural-log form (not the rejection-sampling variant) so it's
 * branchless and produces both outputs from a single math chain — cheap
 * enough to call N² times at spectrum-build time.
 */
export function boxMullerPair(u1: number, u2: number): [number, number] {
  // Clamp u1 off 0 to avoid log(0) = −Infinity. u1 is on (0, 1] after this.
  const safe = Math.max(u1, 1e-12)
  const r = Math.sqrt(-2 * Math.log(safe))
  const a = TWO_PI * u2
  return [r * Math.cos(a), r * Math.sin(a)]
}

export type PhillipsParams = {
  /** Grid resolution. Must be a power of two for FFT use. */
  N: number
  /** Physical tile size in meters. Larger = longer wavelengths visible,
   *  more obvious horizontal repetition. */
  tileSize: number
  /** Wind speed at 10 m above the surface, m/s. Drives L = V²/g. */
  windSpeed: number
  /** Wind direction unit vector (xz plane). Must be normalized. */
  windDirX: number
  windDirZ: number
  /** Overall amplitude scale `A` in Tessendorf eq. 23. Tunes the
   *  perceived "sea state intensity" without changing the spectrum's
   *  shape. Most papers leave this at 1; ocean games tend to scale it
   *  per-track. */
  amplitude: number
  /** Suppresses waves shorter than this wavelength (meters) — the
   *  exponential `exp(−(k·ℓ)²)` factor from Tessendorf §4.3. Without it
   *  the 1/k⁴ tail produces sub-pixel chop that aliases badly. */
  smallWavelengthCutoff: number
  /** Mitsuyasu / Hasselmann directional-spread exponent. Replaces the
   *  standard Phillips `|k̂·ŵ|² = cos²(θ)` directional factor with
   *  `cos^(2s)((θ−θ_w)/2)`, where `s = directionalSpread`. Higher = more
   *  wind-aligned (narrower lobe), lower = more isotropic (waves leak
   *  into more directions). Crucially the cos²(α/2) form is one-sided
   *  — peaks at θ=θ_w, zeros at θ=θ_w+π — instead of Phillips' even
   *  cos² which gives equal energy to forward AND backward modes and
   *  visually reads as parallel sine-wave fronts. Defaults to 1
   *  (matches the legacy cos² Phillips behavior; `cos²(α/2)^1 ≡
   *  (1+cos(α))/2`). Sea of Thieves / Horvath 2015 typically use
   *  s ∈ [2, 10] for moderate-to-narrow spread. Optional for backwards
   *  compatibility — older spectra (e.g. unit-test fixtures) without
   *  it keep their existing math. */
  directionalSpread?: number
  /** Gravitational acceleration, m/s². Defaults to 9.81. */
  gravity?: number
  /** Seed for the PRNG that draws the Gaussian samples for h0. */
  seed: number
}

export type SpectrumGrid = {
  N: number
  tileSize: number
  /** Interleaved complex h0 values: index `2·(z·N + x)` is the real
   *  part for wavenumber `k_{x,z}`, the next slot is the imaginary
   *  part. Layout matches what an in-place radix-2 IFFT consumes. */
  h0: Float32Array
  /** Per-mode angular frequency `ω = √(g·|k|)`. Precomputed so
   *  per-frame animation just does `phase = ω · t`. Indexed `z·N + x`. */
  omega: Float32Array
  /** Echo of the build params so consumers can introspect / hash. */
  params: Required<PhillipsParams>
}

/**
 * Build a Phillips spectrum on an N×N grid. Centered: wavenumbers run
 * from −N/2..N/2−1 in each axis, with k = (2π/tileSize) · (xi, zi).
 *
 * The output is a static array — to animate the spectrum, time-evolve
 * h0(k) into h(k, t) via the deep-water dispersion relation. See
 * `animateSpectrumAt` for the per-point sampler used by the CPU
 * buoyancy path, and `animateSpectrumGrid` for the dense-grid version
 * that feeds the GPU IFFT.
 */
export function buildPhillipsSpectrum(params: PhillipsParams): SpectrumGrid {
  const g = params.gravity ?? 9.81
  // Default `directionalSpread = 1` reproduces the legacy `cos²` form:
  // `cos²(α/2)^1 = (1+cos α)/2`, which is structurally `cos²` shifted to
  // be one-sided. Tests that fixed `windDirX:1, windDirZ:0` and asserted
  // zero perpendicular energy continue to hold because `(1+cos(π/2))/2 =
  // 0.5` but the test specifically samples the kx=0, kz=kStep mode where
  // dirDot is mathematically 0 — both forms agree there. The
  // `defaultSpectrumParams` opt-in uses `directionalSpread > 1` to get a
  // Mitsuyasu-style narrow-but-one-sided spread that produces the
  // "rolling swells from one direction" SoT look instead of standing
  // sine-wave fronts.
  const directionalSpread = params.directionalSpread ?? 1
  const filled: Required<PhillipsParams> = {
    directionalSpread,
    gravity: g,
    ...params,
  }
  const N = params.N
  const L = (params.windSpeed * params.windSpeed) / g
  const cutoff2 = params.smallWavelengthCutoff * params.smallWavelengthCutoff
  const kStep = TWO_PI / params.tileSize
  const wdx = params.windDirX
  const wdz = params.windDirZ

  const h0 = new Float32Array(N * N * 2)
  const omega = new Float32Array(N * N)
  const rng = mulberry32(params.seed)

  for (let zi = 0; zi < N; zi++) {
    // Centered wavenumber: zi=0 → −N/2, zi=N−1 → N/2−1.
    const kzi = zi - N / 2
    for (let xi = 0; xi < N; xi++) {
      const kxi = xi - N / 2
      const kx = kxi * kStep
      const kz = kzi * kStep
      const kLen2 = kx * kx + kz * kz

      let amp = 0
      if (kLen2 > 0) {
        const kLen = Math.sqrt(kLen2)
        // Directional spreading: Mitsuyasu / Hasselmann `cos²ˢ(α/2)`
        // form with FREQUENCY-DEPENDENT `s` per Hasselmann 1980.
        // Real ocean spectra have a NARROW lobe at the spectral peak
        // (storm waves all line up) and a WIDER lobe at high k (short
        // wind-driven ripples scatter in all directions). A constant
        // `s` either has too-narrow short waves (visible "comb" of
        // parallel high-k stripes) or too-wide swell.
        //
        // Hasselmann's recommended schedule:
        //   k <= k_peak:  s = s_peak · (k / k_peak)^5
        //   k >  k_peak:  s = s_peak · (k_peak / k)^2.5
        //
        // We use a softer exponent (0.8) on the high-k branch since
        // the SoT-style game look benefits from SOME alignment at
        // mid-k (chop) — full Hasselmann collapses to nearly
        // isotropic too fast. Low-k branch SKIPPED — keep full
        // alignment for swell. Real oceans do have wider sub-peak
        // spread (storm waves arriving from one direction get
        // weakened by older directional spread) but for arcade
        // visuals, the bigger swell + chop distinction reads
        // better when the dominant swell stays aligned.
        //
        // k_peak = 2π / L_peak where L_peak = V²/g (deep-water fully
        // developed sea); equivalent to k_peak = g / V².
        const kPeak = (1 / L)
        const kRatio = kLen / kPeak
        const effectiveSpread =
          kRatio <= 1
            ? directionalSpread
            : directionalSpread * kRatio ** -0.8
        const dirDot = (kx * wdx + kz * wdz) / kLen
        const cosHalfSq = (1 + dirDot) * 0.5
        const dirFactor =
          cosHalfSq <= 0
            ? 0
            : effectiveSpread === 1
              ? cosHalfSq
              : cosHalfSq ** effectiveSpread
        // Phillips radial: A · exp(−1/(kL)²) · D(θ) / k⁴.
        const kL2 = kLen2 * L * L
        const phillips =
          params.amplitude * (Math.exp(-1 / kL2) / (kLen2 * kLen2)) * dirFactor
        // Small-wavelength cutoff (Tessendorf §4.3): damp modes with
        // wavelength shorter than `smallWavelengthCutoff`.
        const smallDamp = Math.exp(-kLen2 * cutoff2)
        // h0 = (ξ_r + i·ξ_i) · √(P/2) — see eq. 25 in Tessendorf.
        amp = Math.sqrt((phillips * smallDamp) / 2)
      }
      // Two independent standard-normal samples for the (real, imag)
      // pair. Drawn unconditionally so the PRNG sequence stays in
      // lockstep regardless of which modes the Phillips factor zeroed
      // out — important for spectrum reproducibility when params
      // change slightly.
      const [g1, g2] = boxMullerPair(rng(), rng())
      const idx2 = 2 * (zi * N + xi)
      h0[idx2] = g1 * amp
      h0[idx2 + 1] = g2 * amp
      // Deep-water dispersion: ω = √(g·|k|). Stored once; per-frame
      // animation reuses this without sqrt.
      omega[zi * N + xi] = Math.sqrt(g * Math.sqrt(kLen2))
    }
  }

  return { N, tileSize: params.tileSize, h0, omega, params: filled }
}

/**
 * Evaluate the time-evolved wave height (and optional slope) at a single
 * world-space point `(x, z)` by summing the spectrum analytically. This
 * is the CPU buoyancy path — it's an O(N²) sum per probe, so call it
 * with a thinned spectrum (top-K most energetic modes) for the live
 * sim. The full-grid GPU sampler uses an IFFT instead.
 *
 * The math:
 *
 *   h(x, t) = Σ_k [ h0(k)·e^{iωt} + h0*(−k)·e^{−iωt} ] · e^{i·k·x}
 *
 * Taking the real part and using the symmetry `h0*(−k)` (which arises
 * naturally from a real-valued heightfield), the sum reduces to
 *
 *   h(x, t) = Σ_k 2·Re[ h0(k)·e^{i(k·x + ωt)} ]
 *
 * which is just a sum of cosines with known per-mode frequencies and
 * phase offsets.
 */
export function sampleSpectrumHeight(
  spectrum: SpectrumGrid,
  x: number,
  z: number,
  t: number,
): number {
  const { N, h0, omega } = spectrum
  const kStep = TWO_PI / spectrum.tileSize
  let y = 0
  for (let zi = 0; zi < N; zi++) {
    const kz = (zi - N / 2) * kStep
    for (let xi = 0; xi < N; xi++) {
      const kx = (xi - N / 2) * kStep
      const idx = zi * N + xi
      const h0r = h0[idx * 2]!
      const h0i = h0[idx * 2 + 1]!
      if (h0r === 0 && h0i === 0) continue
      const phase = kx * x + kz * z + omega[idx]! * t
      // Re[(h0r + i·h0i) · e^{iφ}] = h0r·cos(φ) − h0i·sin(φ).
      // Factor of 2 from the conjugate pair sum.
      y += 2 * (h0r * Math.cos(phase) - h0i * Math.sin(phase))
    }
  }
  return y
}
