import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import { TransformControls } from 'three/addons/controls/TransformControls.js'
import type { Vec3 } from '@/engine/sim/physics/vec'
import { nearestT, pointAtT, sampleCatmullRom, tangentAtT } from '@/game/tracks/catmull-rom'
import { trackToJson } from '@/game/tracks/json-loader'
import type { BoostPad, Checkpoint, Track } from '@/game/tracks/types'

/**
 * In-app track editor.
 *
 * Workflow:
 *   1. User opens `?track=<id>&edit=1` (default id is `lagoon-edit` — a
 *      JSON snapshot of the procedural Lagoon Loop, generated by
 *      `tools/snapshot_lagoon.mjs`).
 *   2. Sim is paused; this module owns the canvas. It renders every
 *      gameplay entity (gates, pickups, boost pads, AI spline points)
 *      against the water plane.
 *   3. **Outliner panel** lists every entity grouped by kind. Click a row
 *      to select. Selected entity gets a Three.js TransformControls gizmo.
 *   4. **Mode buttons** (Move / Rotate / Scale) — also W / E / R hotkeys —
 *      switch the gizmo between transform modes.
 *      - Pickups + spline points support translate only.
 *      - Gates support translate, rotate (Y axis), and scale (X = half-
 *        width, Y = height).
 *      - Boost pads support translate, rotate (Y axis), and scale (X =
 *        halfWidth, Z = halfDepth).
 *   5. **Place buttons** drop new entities. Click +Gate / +Pickup /
 *      +Boost / +Spline pt, then click on the ground to place. The new
 *      entity is auto-selected.
 *   6. **Save** POSTs to the dev-only `/__editor/save-track` endpoint
 *      which writes `public/tracks/<id>.json`.
 *   7. **Play** reloads without `?edit=1` so you can drive your changes
 *      immediately.
 *
 * Dimensions and scale: helpers are built at the entity's current size
 * with `group.scale = (1,1,1)`. When the user scale-drags the gizmo,
 * `group.scale` grows / shrinks during the drag (the visual stretches
 * uniformly). On drag end we bake the scale into the entity's halfWidth
 * / halfDepth / height fields and rebuild the helper at the new size
 * with scale reset.
 */

export type EditorOptions = {
  scene: THREE.Scene
  camera: THREE.PerspectiveCamera
  renderer: THREE.WebGLRenderer
  domEl: HTMLElement
  track: Track
}

export type EditorHandle = {
  tick(): void
  dispose(): void
}

type GizmoMode = 'translate' | 'rotate' | 'scale'
type PlaceTool = 'none' | 'gate' | 'pickup' | 'pad' | 'spline'

type EntitySel =
  | { kind: 'gate'; index: number }
  | { kind: 'pickup'; index: number }
  | { kind: 'pad'; index: number }
  | { kind: 'spline'; splineIndex: number; pointIndex: number }
  | null

export function installTrackEditor(opts: EditorOptions): EditorHandle {
  const { scene, camera, renderer, domEl, track } = opts
  const draft: Track = JSON.parse(JSON.stringify(track)) as Track
  const canvasEl = renderer.domElement

  // ── Camera + orbit ──────────────────────────────────────────────────────
  camera.position.set(0, 120, 130)
  camera.near = 0.5
  camera.far = 5000
  camera.updateProjectionMatrix()
  camera.lookAt(0, 0, 0)

  const orbit = new OrbitControls(camera, canvasEl)
  orbit.enableDamping = true
  orbit.dampingFactor = 0.08
  orbit.target.set(0, 0, 0)
  orbit.minDistance = 5
  orbit.maxDistance = 600
  orbit.maxPolarAngle = Math.PI / 2 - 0.05

  // ── Transform gizmo ─────────────────────────────────────────────────────
  const tc = new TransformControls(camera, canvasEl)
  // Disable orbit while the user is dragging a gizmo handle. Push an
  // undo snapshot at drag start so Ctrl+Z reverts the entire drag, not
  // each tiny axis update.
  tc.addEventListener('dragging-changed', (e) => {
    const dragging = Boolean(e.value)
    orbit.enabled = !dragging
    if (dragging) pushUndoSnapshot()
    else onGizmoDragEnd()
  })
  // r150+ separates the visual helper from the controller. The helper goes
  // in the scene; the controller is just an event source.
  scene.add(tc.getHelper())

  // ── State ───────────────────────────────────────────────────────────────
  let mode: GizmoMode = 'translate'
  let placeTool: PlaceTool = 'none'
  let sel: EntitySel = null

  // ── Undo stack ──────────────────────────────────────────────────────────
  // Snapshots of the draft are pushed before every "commit-worthy" mutation
  // (placement, delete, gizmo drag start). Ctrl+Z pops + restores.
  const UNDO_LIMIT = 50
  const undoStack: string[] = []

  function pushUndoSnapshot(): void {
    undoStack.push(JSON.stringify(draft))
    if (undoStack.length > UNDO_LIMIT) undoStack.shift()
  }

  function tryUndo(): boolean {
    const snap = undoStack.pop()
    if (!snap) return false
    const restored = JSON.parse(snap) as Track
    // Mutate draft fields in-place so any external references stay valid.
    draft.id = restored.id
    draft.name = restored.name
    draft.lapsToFinish = restored.lapsToFinish
    draft.start = restored.start
    draft.checkpoints = restored.checkpoints
    draft.aiSplines = restored.aiSplines
    draft.pickupSpawns = restored.pickupSpawns
    draft.boostPads = restored.boostPads
    if (restored.water) draft.water = restored.water
    if (restored.environmentGlb) draft.environmentGlb = restored.environmentGlb
    sel = null
    rebuildHelpers()
    renderPanel()
    return true
  }

  // ── Helpers (per-entity 3D objects) ─────────────────────────────────────
  const helpersGroup = new THREE.Group()
  helpersGroup.name = 'editor:helpers'
  scene.add(helpersGroup)
  const helpers = new Map<string, THREE.Group>()
  let splinePolyline: THREE.Line | null = null

  function entityKey(s: NonNullable<EntitySel>): string {
    if (s.kind === 'spline') return `spline:${s.splineIndex}:${s.pointIndex}`
    return `${s.kind}:${s.index}`
  }

  /**
   * Returns the "editable" array of the main spline:
   *  - For Catmull-Rom-anchored splines, that's `anchors`.
   *  - For legacy polyline splines, that's `points`.
   * The dense `points` is always the runtime-consumed output; anchors
   * are the user-facing controls.
   */
  function editableSplinePoints(): Vec3[] {
    const main = draft.aiSplines.find((s) => s.id === 'main')
    if (!main) return []
    return main.anchors ?? main.points
  }

  /**
   * Resample the main spline (if anchored) and reposition any
   * splineT-bound gates to match. Called whenever an anchor moves or
   * a gate's splineT changes.
   */
  function recomputeSplineDerived(): void {
    const main = draft.aiSplines.find((s) => s.id === 'main')
    if (!main) return
    if (main.anchors && main.anchors.length >= 2) {
      main.points = sampleCatmullRom(main.anchors, {
        divisionsPerSegment: 12,
        closed: true,
      })
    }
    for (const cp of draft.checkpoints) {
      if (typeof cp.splineT === 'number') {
        const p = pointAtT(main.points, cp.splineT)
        const tan = tangentAtT(main.points, cp.splineT)
        cp.position.x = p.x
        cp.position.z = p.z
        const yaw = Math.atan2(tan.x, tan.z)
        const halfA = yaw / 2
        cp.rotation = { x: 0, y: Math.sin(halfA), z: 0, w: Math.cos(halfA) }
      }
    }
  }

  function rebuildHelpers(): void {
    tc.detach()
    recomputeSplineDerived()
    for (const h of helpers.values()) {
      helpersGroup.remove(h)
      disposeObj(h)
    }
    helpers.clear()
    if (splinePolyline) {
      helpersGroup.remove(splinePolyline)
      disposeObj(splinePolyline)
      splinePolyline = null
    }

    for (let i = 0; i < draft.checkpoints.length; i++) {
      const k = `gate:${i}`
      const h = makeGateHelper(draft.checkpoints[i]!, isSel({ kind: 'gate', index: i }))
      h.userData.entityKey = k
      helpers.set(k, h)
      helpersGroup.add(h)
    }
    for (let i = 0; i < draft.pickupSpawns.length; i++) {
      const k = `pickup:${i}`
      const h = makePickupHelper(draft.pickupSpawns[i]!, isSel({ kind: 'pickup', index: i }))
      h.userData.entityKey = k
      helpers.set(k, h)
      helpersGroup.add(h)
    }
    for (let i = 0; i < draft.boostPads.length; i++) {
      const k = `pad:${i}`
      const h = makePadHelper(draft.boostPads[i]!, isSel({ kind: 'pad', index: i }))
      h.userData.entityKey = k
      helpers.set(k, h)
      helpersGroup.add(h)
    }
    const main = draft.aiSplines.find((s) => s.id === 'main')
    if (main) {
      const anchors = editableSplinePoints()
      const isAnchored = !!main.anchors
      for (let pi = 0; pi < anchors.length; pi++) {
        const k = `spline:0:${pi}`
        const isSelected = isSel({ kind: 'spline', splineIndex: 0, pointIndex: pi })
        const h = makeAnchorHelper(anchors[pi]!, isSelected, isAnchored)
        h.userData.entityKey = k
        helpers.set(k, h)
        helpersGroup.add(h)
      }
      // Smooth curve drawn from the dense (runtime) sample list.
      splinePolyline = makeSplineCurve(main.points)
      helpersGroup.add(splinePolyline)
    }

    if (sel) {
      const h = helpers.get(entityKey(sel))
      if (h) attachGizmo(h)
      else sel = null
    }
  }

  function isSel(target: NonNullable<EntitySel>): boolean {
    if (!sel) return false
    if (sel.kind !== target.kind) return false
    if (sel.kind === 'spline' && target.kind === 'spline') {
      return sel.pointIndex === target.pointIndex && sel.splineIndex === target.splineIndex
    }
    return (sel as { index: number }).index === (target as { index: number }).index
  }

  function attachGizmo(h: THREE.Object3D): void {
    tc.attach(h)
    tc.setMode(mode)
    const k = (h.userData.entityKey as string) ?? ''
    const kind = k.startsWith('gate')
      ? 'gate'
      : k.startsWith('pad')
        ? 'pad'
        : k.startsWith('pickup')
          ? 'pickup'
          : 'spline'
    // Per-entity axis gating.
    if (kind === 'pickup' || kind === 'spline') {
      // Translate-only entities. Show all three axes for translation.
      tc.showX = true
      tc.showY = true
      tc.showZ = true
    } else if (mode === 'rotate') {
      // Gates / pads rotate around Y only (yaw).
      tc.showX = false
      tc.showY = true
      tc.showZ = false
    } else if (mode === 'scale') {
      // Gates: scale X (halfWidth), Y (height). Pads: scale X (halfWidth), Z (halfDepth).
      if (kind === 'gate') {
        tc.showX = true
        tc.showY = true
        tc.showZ = false
      } else {
        tc.showX = true
        tc.showY = false
        tc.showZ = true
      }
    } else {
      // translate
      tc.showX = true
      tc.showY = true
      tc.showZ = true
    }
  }

  /** Returns whether the currently-selected entity supports a given gizmo
   *  mode. Spline-bound gates derive their rotation from the curve, so
   *  rotate is disabled for those. */
  function selSupportsMode(m: GizmoMode): boolean {
    if (!sel) return true
    if (sel.kind === 'pickup' || sel.kind === 'spline') return m === 'translate'
    if (sel.kind === 'gate') {
      const cp = draft.checkpoints[sel.index]
      if (cp && typeof cp.splineT === 'number' && m === 'rotate') return false
    }
    return true
  }

  function setMode(m: GizmoMode): void {
    if (!selSupportsMode(m)) m = 'translate'
    mode = m
    if (sel) {
      const h = helpers.get(entityKey(sel))
      if (h) attachGizmo(h)
    }
    renderPanel()
  }

  function setSel(newSel: EntitySel): void {
    sel = newSel
    tc.detach()
    if (sel) {
      const h = helpers.get(entityKey(sel))
      if (h) {
        // Force translate mode for entities that don't support the
        // current gizmo mode (eg spline-bound gates can't rotate).
        if (!selSupportsMode(mode)) mode = 'translate'
        attachGizmo(h)
      }
    }
    // Re-tint selection markers without a full rebuild.
    refreshHelperTints()
    renderPanel()
  }

  function refreshHelperTints(): void {
    for (const [k, h] of helpers) {
      const selected = sel != null && k === entityKey(sel)
      const recolor = h.userData.setSelected as ((v: boolean) => void) | undefined
      if (recolor) recolor(selected)
    }
  }

  // ── Gizmo write-back ────────────────────────────────────────────────────
  tc.addEventListener('objectChange', () => {
    const h = tc.object as THREE.Object3D | null
    if (!h || !sel) return
    // Translate + rotate write back live; scale waits for drag end.
    if (mode !== 'scale') writeHelperPoseToDraft(h, sel)
    renderPanelLight()
  })

  function onGizmoDragEnd(): void {
    if (!sel) return
    const h = helpers.get(entityKey(sel))
    if (!h) return
    if (mode === 'scale') {
      // Bake scale into the entity's dimension fields, rebuild geometry at
      // the new size, reset helper.scale to (1,1,1).
      const sx = h.scale.x
      const sy = h.scale.y
      const sz = h.scale.z
      if (sel.kind === 'gate') {
        const cp = draft.checkpoints[sel.index]
        if (cp) {
          cp.halfWidth = clampPositive(cp.halfWidth * sx, 0.5, 200)
          cp.height = clampPositive(cp.height * sy, 0.5, 50)
        }
      } else if (sel.kind === 'pad') {
        const pad = draft.boostPads[sel.index]
        if (pad) {
          pad.halfWidth = clampPositive(pad.halfWidth * sx, 0.5, 50)
          pad.halfDepth = clampPositive(pad.halfDepth * sz, 0.5, 100)
        }
      }
      // Also bake any pose drift that snuck in during the same drag.
      writeHelperPoseToDraft(h, sel)
      rebuildHelpers()
    } else if (sel.kind === 'spline') {
      // Anchor moved → regenerate dense samples + reposition bound gates.
      rebuildHelpers()
    }
    renderPanel()
  }

  function writeHelperPoseToDraft(h: THREE.Object3D, s: NonNullable<EntitySel>): void {
    if (s.kind === 'gate') {
      const cp = draft.checkpoints[s.index]
      if (!cp) return
      if (typeof cp.splineT === 'number') {
        // Spline-bound: project the gizmo's xz onto the nearest point on
        // the curve, snap the helper there, and update splineT. y stays
        // freely editable (gates can sit at different heights).
        const main = draft.aiSplines.find((s2) => s2.id === 'main')
        if (main && main.points.length >= 2) {
          const t = nearestT({ x: h.position.x, y: 0, z: h.position.z }, main.points)
          cp.splineT = t
          const p = pointAtT(main.points, t)
          const tan = tangentAtT(main.points, t)
          cp.position.x = p.x
          cp.position.y = h.position.y
          cp.position.z = p.z
          const yaw = Math.atan2(tan.x, tan.z)
          const halfA = yaw / 2
          cp.rotation = { x: 0, y: Math.sin(halfA), z: 0, w: Math.cos(halfA) }
          // Snap the helper to the resolved pose so the user sees the
          // gate sticking to the curve mid-drag.
          h.position.set(p.x, h.position.y, p.z)
          h.quaternion.set(cp.rotation.x, cp.rotation.y, cp.rotation.z, cp.rotation.w)
        }
        return
      }
      cp.position.x = h.position.x
      cp.position.y = h.position.y
      cp.position.z = h.position.z
      cp.rotation.x = h.quaternion.x
      cp.rotation.y = h.quaternion.y
      cp.rotation.z = h.quaternion.z
      cp.rotation.w = h.quaternion.w
    } else if (s.kind === 'pickup') {
      const p = draft.pickupSpawns[s.index]
      if (!p) return
      p.x = h.position.x
      p.y = h.position.y
      p.z = h.position.z
    } else if (s.kind === 'pad') {
      const pad = draft.boostPads[s.index]
      if (!pad) return
      pad.position.x = h.position.x
      pad.position.y = h.position.y
      pad.position.z = h.position.z
      pad.rotation.x = h.quaternion.x
      pad.rotation.y = h.quaternion.y
      pad.rotation.z = h.quaternion.z
      pad.rotation.w = h.quaternion.w
    } else if (s.kind === 'spline') {
      // Edits the editable array (anchors when present, points for legacy).
      const sp = draft.aiSplines[s.splineIndex]
      if (!sp) return
      const arr = sp.anchors ?? sp.points
      const p = arr[s.pointIndex]
      if (!p) return
      p.x = h.position.x
      p.y = h.position.y
      p.z = h.position.z
      // Live-update the curve + bound-gate poses. Geometry-only refresh
      // (no full rebuildHelpers) for performance during drag.
      recomputeSplineDerived()
      refreshSplineCurveMesh()
      refreshBoundGateHelpers()
    }
  }

  function refreshSplineCurveMesh(): void {
    if (!splinePolyline) return
    const main = draft.aiSplines.find((s) => s.id === 'main')
    if (!main || main.points.length < 2) return
    const arr = (splinePolyline.geometry.attributes.position as THREE.BufferAttribute)
      .array as Float32Array
    // Rebuild only if the buffer is the right size; otherwise rebuild
    // the whole curve mesh.
    const need = (main.points.length + 1) * 3
    if (arr.length !== need) {
      helpersGroup.remove(splinePolyline)
      disposeObj(splinePolyline)
      splinePolyline = makeSplineCurve(main.points)
      helpersGroup.add(splinePolyline)
      return
    }
    for (let i = 0; i < main.points.length; i++) {
      arr[i * 3] = main.points[i]!.x
      arr[i * 3 + 1] = main.points[i]!.y + 0.2
      arr[i * 3 + 2] = main.points[i]!.z
    }
    arr[main.points.length * 3] = main.points[0]!.x
    arr[main.points.length * 3 + 1] = main.points[0]!.y + 0.2
    arr[main.points.length * 3 + 2] = main.points[0]!.z
    ;(splinePolyline.geometry.attributes.position as THREE.BufferAttribute).needsUpdate = true
  }

  function refreshBoundGateHelpers(): void {
    for (let i = 0; i < draft.checkpoints.length; i++) {
      const cp = draft.checkpoints[i]!
      if (typeof cp.splineT !== 'number') continue
      const h = helpers.get(`gate:${i}`)
      if (!h) continue
      h.position.set(cp.position.x, cp.position.y, cp.position.z)
      h.quaternion.set(cp.rotation.x, cp.rotation.y, cp.rotation.z, cp.rotation.w)
    }
  }

  /**
   * Find the index at which a new anchor should be inserted into
   * `anchors` so the curve passes through the click as naturally as
   * possible. Picks the segment whose midpoint is closest to the click.
   */
  function nearestAnchorInsertIndex(hit: THREE.Vector3, anchors: Vec3[]): number {
    if (anchors.length === 0) return 0
    let bestI = anchors.length
    let bestD = Infinity
    for (let i = 0; i < anchors.length; i++) {
      const a = anchors[i]!
      const b = anchors[(i + 1) % anchors.length]!
      const d = distToSegmentXZ(hit.x, hit.z, a.x, a.z, b.x, b.z)
      if (d < bestD) {
        bestD = d
        bestI = i + 1
      }
    }
    return bestI
  }

  function distToSegmentXZ(
    px: number,
    pz: number,
    ax: number,
    az: number,
    bx: number,
    bz: number,
  ): number {
    const dx = bx - ax
    const dz = bz - az
    const len2 = dx * dx + dz * dz
    if (len2 === 0) return Math.hypot(px - ax, pz - az)
    let t = ((px - ax) * dx + (pz - az) * dz) / len2
    t = Math.max(0, Math.min(1, t))
    const cx = ax + t * dx
    const cz = az + t * dz
    return Math.hypot(px - cx, pz - cz)
  }

  // ── DOM panel ───────────────────────────────────────────────────────────
  const panel = document.createElement('div')
  panel.id = 'editor-panel'
  panel.style.cssText = [
    'position: fixed',
    'top: 10px',
    'left: 10px',
    'background: rgba(20,24,30,0.94)',
    'color: #d8e6f0',
    'font: 12px ui-monospace, Menlo, Consolas, monospace',
    'padding: 10px 12px',
    'border: 1px solid #2a3a4a',
    'border-radius: 6px',
    'width: 280px',
    'max-height: calc(100vh - 20px)',
    'display: flex',
    'flex-direction: column',
    'gap: 8px',
    'z-index: 30',
    'pointer-events: auto',
  ].join(';')
  document.body.appendChild(panel)
  // Block pointer events from reaching the renderer when over the panel.
  panel.addEventListener('pointerdown', (e) => e.stopPropagation())
  panel.addEventListener('wheel', (e) => e.stopPropagation())

  function renderPanel(): void {
    panel.innerHTML = panelHtml()
    wirePanelEvents()
  }
  // For high-frequency updates (gizmo dragging) — only update the
  // selected-properties block, not the whole panel.
  function renderPanelLight(): void {
    const propsEl = panel.querySelector('#ed-props')
    if (propsEl) propsEl.innerHTML = selectedPropsHtml()
  }

  function panelHtml(): string {
    return [
      `<div style="font-weight:bold;color:#7fc7ff;font-size:13px">EDITOR · ${escapeHtml(draft.id)}</div>`,
      `<div style="display:flex;flex-direction:column;gap:6px">
         <div style="color:#9bb">Place</div>
         <div style="display:flex;flex-wrap:wrap;gap:4px">
           ${placeBtn('gate', '+ Gate')}
           ${placeBtn('pickup', '+ Pickup')}
           ${placeBtn('pad', '+ Boost')}
           ${placeBtn('spline', '+ Spline pt')}
         </div>
       </div>`,
      `<div style="display:flex;flex-direction:column;gap:6px">
         <div style="color:#9bb">Mode (W / E / R)</div>
         <div style="display:flex;flex-wrap:wrap;gap:4px">
           ${modeBtn('translate', 'Move')}
           ${modeBtn('rotate', 'Rotate')}
           ${modeBtn('scale', 'Scale')}
         </div>
       </div>`,
      `<div id="ed-outliner" style="border-top:1px solid #2a3a4a;padding-top:8px;flex:1;overflow-y:auto;min-height:140px">
         ${outlinerHtml()}
       </div>`,
      `<div id="ed-props" style="border-top:1px solid #2a3a4a;padding-top:8px;font-size:11px;color:#bcd">
         ${selectedPropsHtml()}
       </div>`,
      `<div style="display:flex;gap:6px;border-top:1px solid #2a3a4a;padding-top:8px">
         <button type="button" id="ed-save" style="flex:1;background:#284;color:#dfd;border:1px solid #4a6;padding:6px 10px;border-radius:3px;cursor:pointer">Save</button>
         <button type="button" id="ed-play" style="flex:1;background:#246;color:#dde;border:1px solid #468;padding:6px 10px;border-radius:3px;cursor:pointer">Play</button>
       </div>`,
      `<div id="ed-status" style="color:#7a8;min-height:14px;font-size:11px"></div>`,
      `<div style="color:#778;font-size:10px;line-height:1.4">
        Click in outliner to select · drag gizmo to manipulate<br/>
        L-drag: orbit · R-drag: pan · wheel: zoom<br/>
        Delete = remove · Ctrl+Z = undo · Ctrl+S = save
       </div>`,
    ].join('')
  }

  function placeBtn(t: PlaceTool, label: string): string {
    const on = t === placeTool
    return `<button type="button" data-place="${t}" style="background:${on ? '#a73' : '#234'};color:${on ? '#fff' : '#dde'};border:1px solid ${on ? '#fc8' : '#456'};padding:4px 6px;border-radius:3px;cursor:pointer;font:inherit">${label}</button>`
  }
  function modeBtn(m: GizmoMode, label: string): string {
    const on = m === mode
    const allowed = selSupportsMode(m)
    return `<button type="button" data-mode="${m}" ${allowed ? '' : 'disabled'} style="background:${on ? '#356' : '#234'};color:#dde;border:1px solid ${on ? '#7af' : '#456'};padding:4px 6px;border-radius:3px;cursor:pointer;font:inherit;${allowed ? '' : 'opacity:0.4;cursor:not-allowed'}">${label}</button>`
  }

  function outlinerHtml(): string {
    const sections: string[] = []
    sections.push(
      outlinerSection(
        'Checkpoints',
        draft.checkpoints.map((cp, i) => ({
          k: `gate:${i}`,
          label: `cp_${String(cp.index).padStart(2, '0')}  (${cp.position.x.toFixed(0)}, ${cp.position.z.toFixed(0)})`,
          sel: { kind: 'gate', index: i } as EntitySel,
        })),
      ),
    )
    sections.push(
      outlinerSection(
        'Pickups',
        draft.pickupSpawns.map((p, i) => ({
          k: `pickup:${i}`,
          label: `pickup_${i}  (${p.x.toFixed(0)}, ${p.z.toFixed(0)})`,
          sel: { kind: 'pickup', index: i } as EntitySel,
        })),
      ),
    )
    sections.push(
      outlinerSection(
        'Boost Pads',
        draft.boostPads.map((p, i) => ({
          k: `pad:${i}`,
          label: `pad_${i}  (${p.position.x.toFixed(0)}, ${p.position.z.toFixed(0)})`,
          sel: { kind: 'pad', index: i } as EntitySel,
        })),
      ),
    )
    const main = draft.aiSplines.find((s) => s.id === 'main')
    if (main) {
      const arr = main.anchors ?? main.points
      const isAnchored = !!main.anchors
      const title = isAnchored ? 'Spline anchors' : 'Spline pts'
      const labelPrefix = isAnchored ? 'anchor' : 'pt'
      sections.push(
        outlinerSection(
          title,
          arr.map((p, i) => ({
            k: `spline:0:${i}`,
            label: `${labelPrefix}_${String(i).padStart(2, '0')}  (${p.x.toFixed(0)}, ${p.z.toFixed(0)})`,
            sel: { kind: 'spline', splineIndex: 0, pointIndex: i } as EntitySel,
          })),
        ),
      )
    }
    return sections.join('')
  }

  function outlinerSection(
    title: string,
    items: { k: string; label: string; sel: EntitySel }[],
  ): string {
    const rows = items
      .map((it) => {
        const selected = sel != null && entityKey(sel) === it.k
        const bg = selected ? '#356' : 'transparent'
        const color = selected ? '#fff' : '#bcd'
        return `<div data-select="${it.k}" style="padding:2px 6px;cursor:pointer;border-radius:2px;background:${bg};color:${color}">${escapeHtml(it.label)}</div>`
      })
      .join('')
    return `<div style="margin-bottom:6px">
      <div style="color:#9bb;margin-bottom:2px;font-weight:bold">${title} (${items.length})</div>
      ${rows || '<div style="color:#566;font-size:11px;padding-left:6px">(none)</div>'}
    </div>`
  }

  function selectedPropsHtml(): string {
    if (!sel) return '<span style="color:#566">No selection</span>'
    if (sel.kind === 'gate') {
      const cp = draft.checkpoints[sel.index]
      if (!cp) return '(missing)'
      const bound =
        typeof cp.splineT === 'number'
          ? `<div style="color:#7c9">⚓ bound to spline @ t=${cp.splineT.toFixed(3)}</div>`
          : ''
      return [
        `<div><b>cp_${String(cp.index).padStart(2, '0')}</b></div>`,
        `<div>pos: ${fmtVec(cp.position)}</div>`,
        `<div>halfWidth: ${cp.halfWidth.toFixed(2)} · height: ${cp.height.toFixed(2)}</div>`,
        bound,
      ].join('')
    }
    if (sel.kind === 'pickup') {
      const p = draft.pickupSpawns[sel.index]
      if (!p) return '(missing)'
      return `<div><b>pickup_${sel.index}</b></div><div>pos: ${fmtVec(p)}</div>`
    }
    if (sel.kind === 'pad') {
      const pad = draft.boostPads[sel.index]
      if (!pad) return '(missing)'
      return [
        `<div><b>pad_${sel.index}</b></div>`,
        `<div>pos: ${fmtVec(pad.position)}</div>`,
        `<div>halfWidth: ${pad.halfWidth.toFixed(2)} · halfDepth: ${pad.halfDepth.toFixed(2)} · strength: ${pad.strength.toFixed(2)}</div>`,
      ].join('')
    }
    const sp = draft.aiSplines[sel.splineIndex]
    if (!sp) return '(missing)'
    const arr = sp.anchors ?? sp.points
    const p = arr[sel.pointIndex]
    if (!p) return '(missing)'
    const label = sp.anchors ? 'spline anchor' : 'spline pt'
    return `<div><b>${label} ${sel.pointIndex}</b></div><div>pos: ${fmtVec(p)}</div>`
  }

  function wirePanelEvents(): void {
    const root = panel
    root.querySelectorAll<HTMLElement>('[data-place]').forEach((el) => {
      el.addEventListener('click', () => {
        const t = el.dataset.place as PlaceTool
        placeTool = placeTool === t ? 'none' : t
        renderPanel()
      })
    })
    root.querySelectorAll<HTMLElement>('[data-mode]').forEach((el) => {
      el.addEventListener('click', () => {
        const m = el.dataset.mode as GizmoMode
        setMode(m)
      })
    })
    root.querySelectorAll<HTMLElement>('[data-select]').forEach((el) => {
      el.addEventListener('click', () => {
        const k = el.dataset.select as string
        setSel(parseKey(k))
      })
    })
    root.querySelector('#ed-save')?.addEventListener('click', () => {
      void save()
    })
    root.querySelector('#ed-play')?.addEventListener('click', () => {
      const url = new URL(window.location.href)
      url.searchParams.delete('edit')
      window.location.href = url.toString()
    })
  }

  function parseKey(k: string): EntitySel {
    if (k.startsWith('gate:')) return { kind: 'gate', index: Number(k.slice(5)) }
    if (k.startsWith('pickup:')) return { kind: 'pickup', index: Number(k.slice(7)) }
    if (k.startsWith('pad:')) return { kind: 'pad', index: Number(k.slice(4)) }
    if (k.startsWith('spline:')) {
      const [, si, pi] = k.split(':')
      return { kind: 'spline', splineIndex: Number(si), pointIndex: Number(pi) }
    }
    return null
  }

  // ── Pointer for placement only (selection is via outliner) ──────────────
  const raycaster = new THREE.Raycaster()
  const mouse = new THREE.Vector2()
  const groundPlane = new THREE.Plane(new THREE.Vector3(0, 1, 0), 0)
  const tmpHit = new THREE.Vector3()

  canvasEl.addEventListener('pointerdown', (e) => {
    if (e.button !== 0) return
    if (placeTool === 'none') return
    // Don't intercept drags on the gizmo — only handle bare ground clicks.
    // tc.dragging is true while a handle is grabbed; orbit.enabled flips
    // to false too, but we just guard by checking the gizmo dragging flag.
    if (tc.dragging) return
    const rect = canvasEl.getBoundingClientRect()
    mouse.x = ((e.clientX - rect.left) / rect.width) * 2 - 1
    mouse.y = -((e.clientY - rect.top) / rect.height) * 2 + 1
    raycaster.setFromCamera(mouse, camera)
    if (!raycaster.ray.intersectPlane(groundPlane, tmpHit)) return
    placeAt(tmpHit, placeTool)
    placeTool = 'none'
    renderPanel()
  })

  function placeAt(hit: THREE.Vector3, t: PlaceTool): void {
    pushUndoSnapshot()
    if (t === 'gate') {
      const idx = draft.checkpoints.length
      const main = draft.aiSplines.find((s) => s.id === 'main')
      const useSpline = !!main && main.points.length >= 2
      const cp: Checkpoint = {
        index: idx,
        position: { x: hit.x, y: 1.5, z: hit.z },
        rotation: { x: 0, y: 0, z: 0, w: 1 },
        halfWidth: 8,
        height: 4,
      }
      if (useSpline) {
        // Auto-bind to the main spline at the click's nearest curve point.
        cp.splineT = nearestT({ x: hit.x, y: 0, z: hit.z }, main!.points)
      }
      draft.checkpoints.push(cp)
      sel = { kind: 'gate', index: idx }
    } else if (t === 'pickup') {
      draft.pickupSpawns.push({ x: hit.x, y: 1.2, z: hit.z })
      sel = { kind: 'pickup', index: draft.pickupSpawns.length - 1 }
    } else if (t === 'pad') {
      draft.boostPads.push({
        position: { x: hit.x, y: 0.05, z: hit.z },
        rotation: { x: 0, y: 0, z: 0, w: 1 },
        halfWidth: 3,
        halfDepth: 6,
        strength: 1.5,
      })
      sel = { kind: 'pad', index: draft.boostPads.length - 1 }
    } else if (t === 'spline') {
      const main = draft.aiSplines.find((s) => s.id === 'main')
      if (main) {
        // For Catmull-Rom-anchored splines: insert into anchors at the
        // segment closest to the click so the curve stays continuous.
        // For legacy point-only splines: append to points (preserving
        // the old behavior).
        if (main.anchors && main.anchors.length >= 2) {
          const insertIdx = nearestAnchorInsertIndex(hit, main.anchors)
          main.anchors.splice(insertIdx, 0, { x: hit.x, y: 0.5, z: hit.z })
          sel = { kind: 'spline', splineIndex: 0, pointIndex: insertIdx }
        } else {
          main.points.push({ x: hit.x, y: 0.5, z: hit.z })
          sel = { kind: 'spline', splineIndex: 0, pointIndex: main.points.length - 1 }
        }
      }
    }
    rebuildHelpers()
  }

  // ── Hotkeys ─────────────────────────────────────────────────────────────
  function onKey(e: KeyboardEvent) {
    const tag = (e.target as HTMLElement | null)?.tagName
    if (tag === 'INPUT' || tag === 'TEXTAREA') return
    if (e.code === 'KeyW') setMode('translate')
    else if (e.code === 'KeyE') setMode('rotate')
    else if (e.code === 'KeyR') setMode('scale')
    else if (e.code === 'Delete' || e.code === 'Backspace') {
      if (sel) {
        deleteSelected()
        e.preventDefault()
      }
    } else if (e.code === 'KeyS' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault()
      void save()
    } else if (e.code === 'KeyZ' && (e.ctrlKey || e.metaKey) && !e.shiftKey) {
      e.preventDefault()
      const ok = tryUndo()
      const status = panel.querySelector<HTMLElement>('#ed-status')
      if (status) {
        status.textContent = ok ? `Undid (${undoStack.length} more)` : 'Nothing to undo'
        status.style.color = ok ? '#7a8' : '#aa9'
      }
    } else if (e.code === 'Escape') {
      placeTool = 'none'
      renderPanel()
    }
  }
  window.addEventListener('keydown', onKey)

  function deleteSelected(): void {
    if (!sel) return
    pushUndoSnapshot()
    if (sel.kind === 'gate') {
      draft.checkpoints.splice(sel.index, 1)
      for (let i = 0; i < draft.checkpoints.length; i++) draft.checkpoints[i]!.index = i
    } else if (sel.kind === 'pickup') {
      draft.pickupSpawns.splice(sel.index, 1)
    } else if (sel.kind === 'pad') {
      draft.boostPads.splice(sel.index, 1)
    } else if (sel.kind === 'spline') {
      const sp = draft.aiSplines[sel.splineIndex]
      if (sp) {
        const arr = sp.anchors ?? sp.points
        if (arr.length > 2) arr.splice(sel.pointIndex, 1)
      }
    }
    sel = null
    tc.detach()
    rebuildHelpers()
    renderPanel()
  }

  // ── Save ────────────────────────────────────────────────────────────────
  async function save(): Promise<void> {
    const status = panel.querySelector<HTMLElement>('#ed-status')
    if (status) {
      status.textContent = 'Saving…'
      status.style.color = '#7a8'
    }
    try {
      const res = await fetch('/__editor/save-track', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ id: draft.id, json: trackToJson(draft) }),
      })
      if (!res.ok) {
        const txt = await res.text()
        throw new Error(`${res.status}: ${txt}`)
      }
      const body = (await res.json()) as { path?: string }
      if (status) {
        status.textContent = `Saved → ${body.path ?? 'public/tracks/'}`
        status.style.color = '#7a8'
      }
    } catch (e) {
      if (status) {
        status.textContent = `Save failed: ${(e as Error).message}`
        status.style.color = '#f88'
      }
    }
  }

  // ── Boot ────────────────────────────────────────────────────────────────
  rebuildHelpers()
  renderPanel()

  function tick(): void {
    orbit.update()
    renderer.render(scene, camera)
  }

  function dispose(): void {
    window.removeEventListener('keydown', onKey)
    panel.remove()
    tc.detach()
    tc.dispose()
    orbit.dispose()
    scene.remove(tc.getHelper())
    for (const h of helpers.values()) {
      helpersGroup.remove(h)
      disposeObj(h)
    }
    helpers.clear()
    scene.remove(helpersGroup)
  }

  return { tick, dispose }
}

// ── Helper builders ───────────────────────────────────────────────────────

function makeGateHelper(cp: Checkpoint, selected: boolean): THREE.Group {
  const g = new THREE.Group()
  g.position.set(cp.position.x, cp.position.y, cp.position.z)
  g.quaternion.set(cp.rotation.x, cp.rotation.y, cp.rotation.z, cp.rotation.w)
  // helper.scale stays (1,1,1) — geometry is built at the entity's real
  // dims so the gizmo's scale gestures are intuitive (drag = stretch).

  const baseColor = 0xff7733
  const selColor = 0xffcc66
  const mat = new THREE.MeshBasicMaterial({
    color: selected ? selColor : baseColor,
    transparent: true,
    opacity: 0.9,
  })

  const pillarGeom = new THREE.CylinderGeometry(0.5, 0.5, cp.height, 8)
  const left = new THREE.Mesh(pillarGeom, mat)
  left.position.set(-cp.halfWidth, cp.height / 2, 0)
  g.add(left)
  const right = new THREE.Mesh(pillarGeom, mat.clone())
  right.position.set(cp.halfWidth, cp.height / 2, 0)
  g.add(right)
  const barGeom = new THREE.BoxGeometry(cp.halfWidth * 2, 0.5, 0.4)
  const bar = new THREE.Mesh(barGeom, mat.clone())
  bar.position.set(0, cp.height + 0.25, 0)
  g.add(bar)
  // Forward arrow — small triangle pointing +Z to show gate orientation.
  const arrowGeom = new THREE.ConeGeometry(0.7, 1.4, 4)
  arrowGeom.rotateX(Math.PI / 2) // cone tip toward +Z
  const arrow = new THREE.Mesh(arrowGeom, mat.clone())
  arrow.position.set(0, 0.7, 1.2)
  g.add(arrow)

  g.userData.setSelected = (v: boolean) => {
    g.traverse((c) => {
      const m = (c as THREE.Mesh).material as THREE.MeshBasicMaterial | undefined
      if (m) m.color.setHex(v ? selColor : baseColor)
    })
  }
  return g
}

function makePickupHelper(p: { x: number; y: number; z: number }, selected: boolean): THREE.Group {
  const g = new THREE.Group()
  g.position.set(p.x, p.y, p.z)
  const baseColor = 0xffaa00
  const selColor = 0xffff66
  const mat = new THREE.MeshBasicMaterial({
    color: selected ? selColor : baseColor,
    transparent: true,
    opacity: 0.9,
  })
  const m = new THREE.Mesh(new THREE.SphereGeometry(1.0, 14, 10), mat)
  g.add(m)
  g.userData.setSelected = (v: boolean) => {
    mat.color.setHex(v ? selColor : baseColor)
  }
  return g
}

function makePadHelper(pad: BoostPad, selected: boolean): THREE.Group {
  const g = new THREE.Group()
  g.position.set(pad.position.x, pad.position.y + 0.1, pad.position.z)
  g.quaternion.set(pad.rotation.x, pad.rotation.y, pad.rotation.z, pad.rotation.w)

  const baseColor = 0x33ddff
  const selColor = 0x99ffff
  const w = pad.halfWidth * 2
  const d = pad.halfDepth * 2

  const mat = new THREE.MeshBasicMaterial({
    color: selected ? selColor : baseColor,
    transparent: true,
    opacity: 0.65,
    side: THREE.DoubleSide,
  })
  const slabGeom = new THREE.PlaneGeometry(w, d)
  slabGeom.rotateX(-Math.PI / 2)
  const slab = new THREE.Mesh(slabGeom, mat)
  g.add(slab)
  // Direction arrow pointing +Z (boost direction).
  const arrowGeom = new THREE.ConeGeometry(0.6, 1.2, 4)
  arrowGeom.rotateX(Math.PI / 2)
  const arrow = new THREE.Mesh(
    arrowGeom,
    new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.9 }),
  )
  arrow.position.set(0, 0.05, d * 0.3)
  g.add(arrow)

  g.userData.setSelected = (v: boolean) => {
    mat.color.setHex(v ? selColor : baseColor)
  }
  return g
}

/**
 * Anchor / control-point helper. Bigger (1.2m) when this is a Catmull-Rom
 * anchor — the user is meant to grab and drag these. Smaller (0.6m) for
 * legacy dense polyline points where there are many.
 */
function makeAnchorHelper(
  p: { x: number; y: number; z: number },
  selected: boolean,
  isAnchor: boolean,
): THREE.Group {
  const g = new THREE.Group()
  g.position.set(p.x, p.y + 0.2, p.z)
  const baseColor = isAnchor ? 0x66bbff : 0x88ccff
  const selColor = 0xffff66
  const mat = new THREE.MeshBasicMaterial({ color: selected ? selColor : baseColor })
  const radius = isAnchor ? 1.4 : 0.6
  const segs = isAnchor ? 12 : 8
  const dot = new THREE.Mesh(new THREE.SphereGeometry(radius, segs, segs), mat)
  g.add(dot)
  if (isAnchor) {
    // Faint vertical post so anchors are visible when the camera is low.
    const postMat = new THREE.MeshBasicMaterial({
      color: baseColor,
      transparent: true,
      opacity: 0.4,
    })
    const post = new THREE.Mesh(new THREE.CylinderGeometry(0.15, 0.15, 3, 6), postMat)
    post.position.set(0, 1.5, 0)
    g.add(post)
  }
  g.userData.setSelected = (v: boolean) => {
    mat.color.setHex(v ? selColor : baseColor)
  }
  return g
}

/**
 * Smooth curve drawn from the dense runtime-sample list. For anchored
 * splines this is the Catmull-Rom output; for legacy splines it's just
 * the polyline.
 */
function makeSplineCurve(points: { x: number; y: number; z: number }[]): THREE.Line {
  const geom = new THREE.BufferGeometry()
  if (points.length < 2) {
    geom.setAttribute('position', new THREE.BufferAttribute(new Float32Array(0), 3))
    return new THREE.Line(geom, new THREE.LineBasicMaterial({ color: 0x4488aa }))
  }
  const arr = new Float32Array((points.length + 1) * 3)
  for (let i = 0; i < points.length; i++) {
    arr[i * 3] = points[i]!.x
    arr[i * 3 + 1] = points[i]!.y + 0.2
    arr[i * 3 + 2] = points[i]!.z
  }
  arr[points.length * 3] = points[0]!.x
  arr[points.length * 3 + 1] = points[0]!.y + 0.2
  arr[points.length * 3 + 2] = points[0]!.z
  geom.setAttribute('position', new THREE.BufferAttribute(arr, 3))
  const line = new THREE.Line(geom, new THREE.LineBasicMaterial({ color: 0x66aacc }))
  line.name = 'editor:spline-curve'
  return line
}

// ── Misc utils ────────────────────────────────────────────────────────────

function fmtVec(v: { x: number; y: number; z: number }): string {
  return `(${v.x.toFixed(1)}, ${v.y.toFixed(1)}, ${v.z.toFixed(1)})`
}

function clampPositive(n: number, min: number, max: number): number {
  if (!Number.isFinite(n) || n <= 0) return min
  if (n < min) return min
  if (n > max) return max
  return n
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => {
    if (c === '&') return '&amp;'
    if (c === '<') return '&lt;'
    if (c === '>') return '&gt;'
    if (c === '"') return '&quot;'
    return '&#39;'
  })
}

function disposeObj(o: THREE.Object3D): void {
  o.traverse((c) => {
    const geom = (c as THREE.Mesh).geometry
    if (geom) geom.dispose()
    const m = (c as THREE.Mesh).material
    if (m) {
      if (Array.isArray(m)) {
        for (const mm of m) mm.dispose()
      } else {
        m.dispose()
      }
    }
  })
}
