import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import { TransformControls } from 'three/addons/controls/TransformControls.js'
import type { PropManifestEntry } from '@/game/assets/manifest'
import { nearestT, pointAtT, tangentAtT } from '@/game/tracks/catmull-rom'
import { DEFAULT_GATE_SPACING_M, resampleByArcLength } from '@/game/tracks/gate-placement'
import type { Track } from '@/game/tracks/types'
import {
  createEditorPanel,
  type EditorPanelHandle,
  type EntitySel,
  entityKey,
  type GizmoMode,
  openTrackPickerFlow,
  type PlaceTool,
  parseEntityKey,
  promptNewTrackFlow,
} from './editor-ui'
import {
  bakeScaleToDraft,
  configureGizmoAxes,
  entityKindFromKey,
  selSupportsMode as selSupportsModeFor,
  writeHelperPoseToDraft,
} from './gizmos'
import { createHelpersScene } from './helpers-scene'
import { deleteSelected as deleteSelectedFromDraft, placeAt } from './placement'
import { saveTrack } from './save'
import { recomputeSplineDerived } from './spline-ops'
import { createUndoStack } from './undo-redo'

/**
 * In-app track editor.
 *
 * Workflow:
 *   1. User opens `?track=<id>&edit=1` (default id is `lagoon-edit` — a
 *      JSON snapshot of the procedural Lagoon Loop, generated by
 *      `tools/snapshot_lagoon.mjs`).
 *   2. Sim is paused; this module owns the canvas. It renders every
 *      gameplay entity (gates, pickups, boost pads, AI spline points)
 *      against the water plane.
 *   3. **Outliner panel** lists every entity grouped by kind. Click a row
 *      to select. Selected entity gets a Three.js TransformControls gizmo.
 *   4. **Mode buttons** (Move / Rotate / Scale) — also W / E / R hotkeys —
 *      switch the gizmo between transform modes.
 *      - Pickups + spline points support translate only.
 *      - Gates support translate, rotate (Y axis), and scale (X = half-
 *        width, Y = height).
 *      - Boost pads support translate, rotate (Y axis), and scale on
 *        all three axes (X = halfWidth, Y = halfHeight, Z = halfDepth)
 *        — pads are 3D trigger volumes, not flat slabs.
 *   5. **Place buttons** drop new entities. Click +Gate / +Pickup /
 *      +Boost / +Spline pt, then click on the ground to place. The new
 *      entity is auto-selected.
 *   6. **Save** POSTs to the dev-only `/__editor/save-track` endpoint
 *      which writes `public/tracks/<id>.json`.
 *   7. **Play** reloads without `?edit=1` so you can drive your changes
 *      immediately.
 *
 * Dimensions and scale: helpers are built at the entity's current size
 * with `group.scale = (1,1,1)`. When the user scale-drags the gizmo,
 * `group.scale` grows / shrinks during the drag (the visual stretches
 * uniformly). On drag end we bake the scale into the entity's halfWidth
 * / halfDepth / height fields and rebuild the helper at the new size
 * with scale reset.
 *
 * This file is the orchestrator — gizmo wiring, raycast routing, panel
 * callbacks, hotkey routing. Per-concern helpers live in sibling files:
 *   - `editor-helpers.ts` — per-entity 3D helper-mesh factories
 *   - `editor-ui.ts` — DOM panel + modal flows
 *   - `gizmos.ts` — gizmo axis gating + helper-pose write-back
 *   - `helpers-scene.ts` — owns the helpers-group + rebuild + tint refresh
 *   - `placement.ts` — placeAt + deleteSelected per-kind branches
 *   - `spline-ops.ts` — spline math (resampling, nearest-segment)
 *   - `save.ts` — save POST
 *   - `undo-redo.ts` — snapshot stack
 */

export type EditorOptions = {
  scene: THREE.Scene
  camera: THREE.PerspectiveCamera
  renderer: THREE.WebGLRenderer
  domEl: HTMLElement
  track: Track
  /** Available asset-prop manifest entries. Surfaces a +Asset placement
   *  dropdown that drops `{ type: 'asset', assetId }` props the runtime
   *  later loads from `public/assets/props/<assetId>.glb`. */
  propAssets?: PropManifestEntry[]
  /** Live-shifts the rendered sea level when the panel's water-height
   *  slider drags. Optional so headless / test wiring still works.
   *  Wave amplitudes oscillate around this Y. */
  setWaterHeight?: (heightM: number) => void
}

export type EditorHandle = {
  tick(): void
  dispose(): void
}

export function installTrackEditor(opts: EditorOptions): EditorHandle {
  const { scene, camera, renderer, track } = opts
  const draft: Track = JSON.parse(JSON.stringify(track)) as Track
  if (!Array.isArray(draft.props)) draft.props = []
  const canvasEl = renderer.domElement

  // ── Camera + orbit ──────────────────────────────────────────────────────
  camera.position.set(0, 120, 130)
  camera.near = 0.5
  camera.far = 5000
  camera.updateProjectionMatrix()
  camera.lookAt(0, 0, 0)

  const orbit = new OrbitControls(camera, canvasEl)
  orbit.enableDamping = true
  orbit.dampingFactor = 0.08
  orbit.target.set(0, 0, 0)
  orbit.minDistance = 5
  orbit.maxDistance = 600
  orbit.maxPolarAngle = Math.PI / 2 - 0.05

  // ── Transform gizmo ─────────────────────────────────────────────────────
  const tc = new TransformControls(camera, canvasEl)
  // Disable orbit while the user is dragging a gizmo handle. Push an
  // undo snapshot at drag start so Ctrl+Z reverts the entire drag, not
  // each tiny axis update.
  tc.addEventListener('dragging-changed', (e) => {
    const dragging = Boolean(e.value)
    orbit.enabled = !dragging
    if (dragging) undo.push()
    else onGizmoDragEnd()
  })
  // r150+ separates the visual helper from the controller. The helper goes
  // in the scene; the controller is just an event source.
  scene.add(tc.getHelper())

  // ── State ───────────────────────────────────────────────────────────────
  let mode: GizmoMode = 'translate'
  let placeTool: PlaceTool = 'none'
  let sel: EntitySel = null

  // Manifest-driven asset props for the +Asset placer.
  const propAssets: PropManifestEntry[] = opts.propAssets ?? []
  let pickedAssetId: string = propAssets[0]?.id ?? ''
  // Water-height slider: coalesce undo across one drag session so
  // Ctrl+Z reverts the whole adjustment rather than each ~1mm tick.
  // Cleared whenever the user mouseups (next non-water interaction
  // pushes its own snapshot).
  let waterDragSnapshotted = false
  // Same pattern for the start-on-spline t slider — one undo entry per
  // drag rather than one per slider tick.
  let startTDragSnapshotted = false

  // ── Undo stack ──────────────────────────────────────────────────────────
  const undo = createUndoStack(draft, () => {
    sel = null
    rebuildHelpers()
    renderPanel()
  })

  // ── Helpers scene ───────────────────────────────────────────────────────
  const helpersScene = createHelpersScene({ scene, draft, getSel: () => sel })

  function rebuildHelpers(): void {
    tc.detach()
    helpersScene.rebuild()
    if (sel) {
      const h = helpersScene.helpers.get(entityKey(sel))
      if (h) attachGizmo(h)
      else sel = null
    }
  }

  function attachGizmo(h: THREE.Object3D): void {
    tc.attach(h)
    tc.setMode(mode)
    const k = (h.userData.entityKey as string) ?? ''
    configureGizmoAxes(tc, entityKindFromKey(k), mode)
  }

  function selSupportsMode(m: GizmoMode): boolean {
    return selSupportsModeFor(draft, sel, m)
  }

  function setMode(m: GizmoMode): void {
    if (!selSupportsMode(m)) m = 'translate'
    mode = m
    if (sel) {
      const h = helpersScene.helpers.get(entityKey(sel))
      if (h) attachGizmo(h)
    }
    renderPanel()
  }

  function setSel(newSel: EntitySel): void {
    sel = newSel
    tc.detach()
    if (sel) {
      const h = helpersScene.helpers.get(entityKey(sel))
      if (h) {
        // Force translate mode for entities that don't support the
        // current gizmo mode (eg spline-bound gates can't rotate).
        if (!selSupportsMode(mode)) mode = 'translate'
        attachGizmo(h)
      }
    }
    // Re-tint selection markers without a full rebuild.
    helpersScene.refreshTints(sel)
    renderPanel()
  }

  // ── Gizmo write-back ────────────────────────────────────────────────────
  tc.addEventListener('objectChange', () => {
    const h = tc.object as THREE.Object3D | null
    if (!h || !sel) return
    // Translate + rotate write back live; scale waits for drag end.
    if (mode !== 'scale') {
      const { splineMoved } = writeHelperPoseToDraft(draft, h, sel)
      if (splineMoved) {
        // Anchor moved: regenerate dense curve samples + reposition any
        // bound gates. Geometry-only refresh (no full rebuildHelpers) for
        // perf during drag.
        recomputeSplineDerived(draft)
        helpersScene.refreshSplineCurveMesh()
        helpersScene.refreshBoundGateHelpers()
      }
    }
    renderPanelLight()
  })

  function onGizmoDragEnd(): void {
    if (!sel) return
    const h = helpersScene.helpers.get(entityKey(sel))
    if (!h) return
    if (mode === 'scale') {
      // Bake scale into the entity's dimension fields, rebuild geometry at
      // the new size, reset helper.scale to (1,1,1).
      bakeScaleToDraft(draft, h, sel)
      // Also bake any pose drift that snuck in during the same drag.
      writeHelperPoseToDraft(draft, h, sel)
      rebuildHelpers()
    } else if (sel.kind === 'spline') {
      // Anchor moved → regenerate dense samples + reposition bound gates.
      rebuildHelpers()
    }
    renderPanel()
  }

  // ── DOM panel ───────────────────────────────────────────────────────────
  // The panel UI itself lives in `editor-ui.ts`. We pass a `getState`
  // callback so the panel reads the current sel/mode/placeTool on each
  // render, and a callbacks bag so user interactions flow back into the
  // closure mutations (setMode/setSel/save/etc).
  const panelHandle: EditorPanelHandle = createEditorPanel({
    draft,
    propAssets,
    getState: () => ({ sel, mode, placeTool, pickedAssetId }),
    callbacks: {
      onPlaceTool: (t) => {
        placeTool = placeTool === t ? 'none' : t
        panelHandle.render()
      },
      onMode: (m) => setMode(m),
      onSelect: (s) => setSel(s),
      onAssetPick: (id) => {
        pickedAssetId = id
      },
      onSave: () => {
        void save()
      },
      onPlay: () => {
        const url = new URL(window.location.href)
        url.searchParams.delete('edit')
        window.location.href = url.toString()
      },
      onOpen: () => {
        void openTrackPickerFlow({
          currentTrackId: draft.id,
          confirmDiscard,
          setStatus: (msg, color) => panelHandle.setStatus(msg, color),
        })
      },
      onNew: () => {
        promptNewTrackFlow({ currentTrackId: draft.id, confirmDiscard })
      },
      onWaterHeightCommit: () => {
        waterDragSnapshotted = false
      },
      onStartBindToSpline: () => {
        const main = draft.aiSplines.find((s) => s.id === 'main')
        if (!main || main.points.length < 2) {
          panelHandle.setStatus('Bind start: no main spline', '#f88')
          return
        }
        undo.push()
        const t = nearestT(
          { x: draft.start.position.x, y: 0, z: draft.start.position.z },
          main.points,
        )
        const p = pointAtT(main.points, t)
        const tan = tangentAtT(main.points, t)
        draft.start.splineT = t
        draft.start.position = { x: p.x, y: draft.start.position.y, z: p.z }
        draft.start.yaw = Math.atan2(tan.x, tan.z)
        rebuildHelpers()
        renderPanel()
        panelHandle.setStatus(`Start bound to spline @ t=${t.toFixed(3)}`, '#7d8')
      },
      onStartUnbindFromSpline: () => {
        if (typeof draft.start.splineT !== 'number') return
        undo.push()
        delete draft.start.splineT
        rebuildHelpers()
        renderPanel()
        panelHandle.setStatus('Start unbound — free placement', '#7d8')
      },
      onStartSplineTChange: (t: number) => {
        if (typeof draft.start.splineT !== 'number') return
        const main = draft.aiSplines.find((s) => s.id === 'main')
        if (!main || main.points.length < 2) return
        const current = draft.start.splineT
        if (Math.abs(current - t) < 1e-5) return
        if (!startTDragSnapshotted) {
          undo.push()
          startTDragSnapshotted = true
        }
        draft.start.splineT = ((t % 1) + 1) % 1
        const p = pointAtT(main.points, draft.start.splineT)
        const tan = tangentAtT(main.points, draft.start.splineT)
        draft.start.position.x = p.x
        draft.start.position.z = p.z
        draft.start.yaw = Math.atan2(tan.x, tan.z)
        // Reposition just the start helper rather than a full rebuild —
        // the rest of the scene doesn't change while we slide the slider.
        helpersScene.refreshBoundGateHelpers()
        renderPanelLight()
      },
      onStartSplineTCommit: () => {
        startTDragSnapshotted = false
        // Full panel render so the outliner row's xz/yaw caption catches up
        // with the slid-to value (renderLight only refreshes the props block).
        renderPanel()
      },
      onWaterHeightChange: (h: number) => {
        // The slider streams every tick — coalesce undo by snapshotting
        // once when the user *first* nudges the value this session and
        // letting subsequent drags overwrite. Cheap heuristic: if the
        // last undo entry already snapped at the current value, skip.
        const current = draft.water?.height ?? 0
        if (Math.abs(current - h) < 1e-4) return
        if (!waterDragSnapshotted) {
          undo.push()
          waterDragSnapshotted = true
        }
        if (!draft.water) {
          draft.water = { height: h }
        } else {
          draft.water.height = h
        }
        opts.setWaterHeight?.(h)
      },
      onAutoPlaceGates: () => {
        const main = draft.aiSplines.find((s) => s.id === 'main')
        if (!main || main.points.length < 2) {
          panelHandle.setStatus('Auto-place: no main spline available', '#f88')
          return
        }
        const spacing =
          typeof draft.gateSpacing === 'number' && draft.gateSpacing > 0
            ? draft.gateSpacing
            : DEFAULT_GATE_SPACING_M
        const placements = resampleByArcLength(main.points, spacing)
        if (placements.length === 0) {
          panelHandle.setStatus('Auto-place: spline has zero length', '#f88')
          return
        }
        if (!confirmDiscard('Replace gates')) return
        undo.push()
        // Preserve halfWidth / height from the existing first gate if present;
        // fall back to the project's canonical gate dimensions otherwise.
        const inheritedHalfWidth = draft.checkpoints[0]?.halfWidth ?? 14
        const inheritedHeight = draft.checkpoints[0]?.height ?? 6
        draft.checkpoints = placements.map((p, i) => ({
          index: i,
          position: { x: p.position.x, y: 1.5, z: p.position.z },
          rotation: { x: 0, y: 0, z: 0, w: 1 },
          halfWidth: inheritedHalfWidth,
          height: inheritedHeight,
          splineT: p.t,
        }))
        sel = null
        rebuildHelpers()
        panelHandle.render()
        panelHandle.setStatus(`Placed ${placements.length} gates at ${spacing.toFixed(0)}m`, '#7d8')
      },
      selSupportsMode,
    },
  })

  // Lightweight aliases so the rest of the closure can keep calling
  // `renderPanel()` / `renderPanelLight()` without threading the handle
  // through every callsite.
  function renderPanel(): void {
    panelHandle.render()
  }
  function renderPanelLight(): void {
    panelHandle.renderLight()
  }

  function confirmDiscard(action: string): boolean {
    if (!undo.isDirty()) return true
    return window.confirm(
      `You have unsaved changes. ${action} anyway?\n\nUnsaved changes will be lost.`,
    )
  }

  // ── Pointer for placement only (selection is via outliner) ──────────────
  const raycaster = new THREE.Raycaster()
  const mouse = new THREE.Vector2()
  const groundPlane = new THREE.Plane(new THREE.Vector3(0, 1, 0), 0)
  const tmpHit = new THREE.Vector3()

  canvasEl.addEventListener('pointerdown', (e) => {
    if (e.button !== 0) return
    // Don't intercept drags on the gizmo — only handle bare ground clicks.
    // tc.dragging is true while a handle is grabbed; orbit.enabled flips
    // to false too, but we just guard by checking the gizmo dragging flag.
    if (tc.dragging) return
    const rect = canvasEl.getBoundingClientRect()
    mouse.x = ((e.clientX - rect.left) / rect.width) * 2 - 1
    mouse.y = -((e.clientY - rect.top) / rect.height) * 2 + 1
    raycaster.setFromCamera(mouse, camera)

    if (placeTool !== 'none') {
      if (!raycaster.ray.intersectPlane(groundPlane, tmpHit)) return
      undo.push()
      sel = placeAt({ draft, hit: tmpHit, tool: placeTool, pickedAssetId })
      placeTool = 'none'
      rebuildHelpers()
      renderPanel()
      return
    }

    // Viewport selection: raycast against helper geometry and pick the
    // owning helper group via its userData.entityKey marker.
    const hits = raycaster.intersectObjects(helpersScene.group.children, true)
    let pickedKey: string | null = null
    for (const hit of hits) {
      let cur: THREE.Object3D | null = hit.object
      while (cur && cur !== helpersScene.group) {
        const ek = cur.userData.entityKey as string | undefined
        if (ek) {
          pickedKey = ek
          break
        }
        cur = cur.parent
      }
      if (pickedKey) break
    }
    if (pickedKey) {
      setSel(parseEntityKey(pickedKey))
    } else {
      // Click on empty space → deselect.
      setSel(null)
    }
  })

  // ── Hotkeys ─────────────────────────────────────────────────────────────
  function onKey(e: KeyboardEvent) {
    const tag = (e.target as HTMLElement | null)?.tagName
    if (tag === 'INPUT' || tag === 'TEXTAREA') return
    if (e.code === 'KeyW') setMode('translate')
    else if (e.code === 'KeyE') setMode('rotate')
    else if (e.code === 'KeyR') setMode('scale')
    else if (e.code === 'Delete' || e.code === 'Backspace') {
      if (sel) {
        deleteSelected()
        e.preventDefault()
      }
    } else if (e.code === 'KeyS' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault()
      void save()
    } else if (e.code === 'KeyZ' && (e.ctrlKey || e.metaKey) && !e.shiftKey) {
      e.preventDefault()
      const ok = undo.tryUndo()
      panelHandle.setStatus(
        ok ? `Undid (${undo.depth()} more)` : 'Nothing to undo',
        ok ? '#7a8' : '#aa9',
      )
    } else if (e.code === 'Escape') {
      placeTool = 'none'
      renderPanel()
    }
  }
  window.addEventListener('keydown', onKey)

  function deleteSelected(): void {
    if (!sel) return
    if (sel.kind === 'start') return // start is a singleton — cannot be deleted
    undo.push()
    deleteSelectedFromDraft(draft, sel)
    sel = null
    tc.detach()
    rebuildHelpers()
    renderPanel()
  }

  // ── Save ────────────────────────────────────────────────────────────────
  async function save(): Promise<void> {
    await saveTrack({
      draft,
      setStatus: (msg, color) => panelHandle.setStatus(msg, color),
      onSaved: () => undo.markSaved(),
    })
  }

  // ── Boot ────────────────────────────────────────────────────────────────
  rebuildHelpers()
  renderPanel()

  function tick(): void {
    orbit.update()
    renderer.render(scene, camera)
  }

  function dispose(): void {
    window.removeEventListener('keydown', onKey)
    panelHandle.dispose()
    tc.detach()
    tc.dispose()
    orbit.dispose()
    scene.remove(tc.getHelper())
    helpersScene.dispose()
  }

  return { tick, dispose }
}
