/**
 * Renders the orchestrator's run data as a single Markdown document.
 * Kept separate from runner.mjs so unit tests (and future re-runs that
 * want to consume an older qa-report.json) can build the same view
 * without re-running the gates.
 *
 * The report is opinionated: one summary table, one per-step section
 * each with a status pill and a pointer at the log file. Failures get
 * a tail of the log inline so a triager doesn't have to chase the
 * artifact path.
 */

import { existsSync, readFileSync } from 'node:fs'

/** Number of trailing log lines to inline under a failure section. */
const FAILURE_TAIL_LINES = 40

/**
 * @typedef {{
 *   schemaVersion: 1,
 *   runStartedAt: string,
 *   runFinishedAt: string,
 *   runDurationMs: number,
 *   repoRoot: string,
 *   steps: QaStep[],
 * }} QaReport
 * @typedef {{
 *   id: string,
 *   label: string,
 *   command: string,
 *   status: 'pass' | 'fail' | 'skip',
 *   durationMs: number,
 *   startedAt: string,
 *   finishedAt: string,
 *   exitCode: number | null,
 *   logPath: string,
 *   gate: boolean,
 * }} QaStep
 */

const STATUS_GLYPH = Object.freeze({
  pass: '✅ PASS',
  fail: '❌ FAIL',
  skip: '⏭️ SKIP',
})

/** @param {QaReport} report */
export function renderMarkdown(report) {
  const lines = []
  const totals = summariseTotals(report.steps)
  const shippable = report.steps.every((s) => s.status !== 'fail' || !s.gate)

  lines.push('# Hoverbike QA Report')
  lines.push('')
  lines.push(`> Run started **${report.runStartedAt}** — ${formatDuration(report.runDurationMs)}.`)
  lines.push('')
  lines.push(
    shippable
      ? '**Shippability:** ✅ no gated failures.'
      : '**Shippability:** ❌ one or more gated steps failed — see per-step sections below.',
  )
  lines.push('')

  // Summary table — one line per step.
  lines.push('## Summary')
  lines.push('')
  lines.push('| Step | Status | Duration | Gate | Log |')
  lines.push('|---|---|---|---|---|')
  for (const s of report.steps) {
    lines.push(
      `| ${s.label} | ${STATUS_GLYPH[s.status]} | ${formatDuration(s.durationMs)} | ${s.gate ? 'yes' : 'no'} | \`${relPath(s.logPath, report.repoRoot)}\` |`,
    )
  }
  lines.push('')
  lines.push(
    `**Totals:** ${totals.pass} pass · ${totals.fail} fail · ${totals.skip} skip · ${report.steps.length} total.`,
  )
  lines.push('')

  // Per-step section, with a log tail for failures.
  lines.push('## Per-step detail')
  lines.push('')
  for (const s of report.steps) {
    lines.push(`### ${STATUS_GLYPH[s.status]} ${s.label}`)
    lines.push('')
    lines.push(`- **id:** \`${s.id}\``)
    lines.push(`- **command:** \`${s.command}\``)
    lines.push(`- **exit code:** \`${s.exitCode}\``)
    lines.push(`- **duration:** ${formatDuration(s.durationMs)}`)
    lines.push(`- **gate:** ${s.gate ? 'yes — failure blocks shippability' : 'no — advisory only'}`)
    lines.push(`- **log:** \`${relPath(s.logPath, report.repoRoot)}\``)
    if (s.status === 'fail') {
      const tail = readLogTail(s.logPath, FAILURE_TAIL_LINES)
      if (tail) {
        lines.push('')
        lines.push('<details>')
        lines.push(`<summary>Last ${FAILURE_TAIL_LINES} log lines</summary>`)
        lines.push('')
        lines.push('```')
        lines.push(tail)
        lines.push('```')
        lines.push('')
        lines.push('</details>')
      }
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push(
    `Generated by \`tools/qa/runner.mjs\` at ${report.runFinishedAt}. See [docs/qa-playbook.md](../docs/qa-playbook.md) for the convention.`,
  )
  lines.push('')
  return lines.join('\n')
}

/** Count statuses across steps. Pure; used by both the renderer and the
 *  orchestrator's stdout one-liner. */
export function summariseTotals(steps) {
  const t = { pass: 0, fail: 0, skip: 0 }
  for (const s of steps) {
    t[s.status] = (t[s.status] ?? 0) + 1
  }
  return t
}

function relPath(absPath, root) {
  if (!absPath) return ''
  // `root` may or may not carry a trailing slash depending on how the
  // caller resolved it. Normalise both sides so the slice doesn't eat
  // a leading character of the relative tail.
  const normRoot = root.endsWith('/') ? root : `${root}/`
  if (absPath.startsWith(normRoot)) return absPath.slice(normRoot.length)
  return absPath
}

function formatDuration(ms) {
  if (ms < 1000) return `${ms}ms`
  if (ms < 60_000) return `${(ms / 1000).toFixed(1)}s`
  const minutes = Math.floor(ms / 60_000)
  const seconds = Math.floor((ms % 60_000) / 1000)
  return `${minutes}m ${seconds}s`
}

function readLogTail(path, n) {
  if (!existsSync(path)) return ''
  try {
    const raw = readFileSync(path, 'utf8')
    const lines = raw.split('\n')
    return lines.slice(Math.max(0, lines.length - n)).join('\n')
  } catch {
    return ''
  }
}
