// AUTO-GENERATED by tools/convert-music.mjs — do not edit by hand.
// Regenerate with: pnpm gen:music
//
// Source: 14 licensed track(s), transcoded to Opus @ 112k VBR.
// Credits are parsed from the "<artist> - <title>.mp3" source filenames.

import type { SoundtrackEntry } from './soundtrack'

export const SOUNDTRACK: readonly SoundtrackEntry[] = [
  { file: "artificial-intelligence-suddenly-it-occurs-to-me-theres-no-ocean-here.opus", artist: "Artificial Intelligence", title: "Suddenly It Occurs To Me There's No Ocean Here" },
  { file: "atomicos-rad-racer.opus", artist: "Atomicos", title: "Rad Racer" },
  { file: "avantist-tidalwave.opus", artist: "Avantist", title: "Tidalwave" },
  { file: "blue-wave-theory-900-turbo.opus", artist: "Blue Wave Theory", title: "900 Turbo" },
  { file: "blue-wave-theory-frisbeat.opus", artist: "Blue Wave Theory", title: "Frisbeat" },
  { file: "blue-wave-theory-get-your-kicks-on-future-86.opus", artist: "Blue Wave Theory", title: "Get Your Kicks on Future 86" },
  { file: "blue-wave-theory-road-hazard.opus", artist: "Blue Wave Theory", title: "Road Hazard" },
  { file: "checkie-brown-hawaii-5-0-cb-203.opus", artist: "Checkie Brown", title: "Hawaii 5-0 (CB 203)" },
  { file: "crowander-beach-party.opus", artist: "Crowander", title: "Beach Party" },
  { file: "crowander-whisky.opus", artist: "Crowander", title: "Whisky" },
  { file: "holiznacc0-western-showdown.opus", artist: "HoliznaCC0", title: "Western ShowDown" },
  { file: "mr-smith-twango.opus", artist: "Mr Smith", title: "Twango" },
  { file: "untimely-dosage-bum-lyfe.opus", artist: "Untimely Dosage", title: "Bum Lyfe" },
  { file: "vlad-annenkov-sunny-positive-surf-rock-sandy-shores.opus", artist: "Vlad Annenkov", title: "Sunny Positive Surf Rock (Sandy Shores)" },
]
