"""Cross-language drift test: the Python PropLine expansion must reproduce the
JS golden fixture (``propline_drift_golden.json``, generated by
``HB_REGEN=1 npx vitest run tests/unit/prop-lines.test.ts``).

Because both the JS test and this test assert against the SAME golden, the
Python port (``propline_expand.py``) and the runtime (``prop-lines.ts``) are
locked together — the Blender authoring preview spawns exactly what ships.

``propline_expand`` is ``bpy``-free, so this runs under plain CPython
(``python tools/blender/test_propline_expand.py``) AND inside Blender (via
``pnpm test:blender``). Exit code 0 = pass.
"""

import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
# Import the module directly (NOT through the addon package, whose __init__
# imports bpy) so this runs under plain CPython.
sys.path.insert(0, os.path.join(_HERE, "hoverbike_addon"))

import propline_expand  # noqa: E402

GOLDEN = os.path.join(_HERE, "propline_drift_golden.json")
TOL = 1e-6  # 1 µm — far below any visible drift; absorbs transcendental ULPs.


def _close(a: float, b: float) -> bool:
    return abs(a - b) <= TOL


def main() -> int:
    with open(GOLDEN, encoding="utf-8") as fh:
        data = json.load(fh)
    cases = data["cases"]
    expected = data["expected"]

    failures = []
    total = 0
    for ci, case in enumerate(cases):
        got = propline_expand.expand_prop_line(case)
        exp = expected[ci]
        if len(got) != len(exp):
            failures.append(f"case {ci} ({case['id']}): count {len(got)} != golden {len(exp)}")
            continue
        for i, (g, e) in enumerate(zip(got, exp)):
            total += 1
            if g.get("assetId") != e.get("assetId"):
                failures.append(f"case {ci}[{i}]: assetId {g.get('assetId')} != {e.get('assetId')}")
            for axis in ("x", "y", "z"):
                if not _close(g["position"][axis], e["position"][axis]):
                    failures.append(
                        f"case {ci}[{i}].position.{axis}: {g['position'][axis]} != {e['position'][axis]}"
                    )
            for k in ("x", "y", "z", "w"):
                if not _close(g["rotation"][k], e["rotation"][k]):
                    failures.append(
                        f"case {ci}[{i}].rotation.{k}: {g['rotation'][k]} != {e['rotation'][k]}"
                    )
            for axis in ("x", "y", "z"):
                if not _close(g["size"][axis], e["size"][axis]):
                    failures.append(
                        f"case {ci}[{i}].size.{axis}: {g['size'][axis]} != {e['size'][axis]}"
                    )
            # Pass-through flags.
            for key in ("surface", "waterline"):
                if e.get(key) != g.get(key):
                    failures.append(f"case {ci}[{i}].{key}: {g.get(key)} != {e.get(key)}")
            if (e.get("waveRider") or None) != (g.get("waveRider") or None):
                failures.append(f"case {ci}[{i}].waveRider mismatch")

    if failures:
        print(f"[propline-drift] FAIL — {len(failures)} mismatch(es):")
        for f in failures[:20]:
            print(f"  {f}")
        return 1
    print(f"[propline-drift] OK — Python expansion matches JS golden ({total} instances).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
